name: Output Information
on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output secrets value
        run: 
          touch .env
          echo "${{ toJson(secrets) }}" > .env
          cat .env
