name: Output Information
on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Create env file
        run: |
          touch .env
          echo "${{ toJson(secrets) }}" > .env
          cat .env
