name: Output Information
on: 
  push:
    branches:
      - master
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output secrets value
        run: echo "${{ toJson(secrets) }}" > .env
